name: 🐛 Bug Report
description: Report bugs or technical issues with AI Logica
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in AI Logica! This template will help ensure your report includes all the information needed for effective debugging and resolution.
        
        📖 **Please review the existing documentation first:**
        - [REQUIREMENTS.md](../blob/main/REQUIREMENTS.md) - Current functional requirements
        - [DEVELOPER_GUIDE.md](../blob/main/DEVELOPER_GUIDE.md) - Development guidelines and standards
        - [ARCHITECTURE.md](../blob/main/ARCHITECTURE.md) - Technical architecture overview

  - type: textarea
    id: bug-description
    attributes:
      label: "Bug Description"
      description: "Provide a clear and concise description of the bug"
      placeholder: "Describe what happened and what you expected to happen instead..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the issue"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What should have happened instead?"
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: dropdown
    id: bug-category
    attributes:
      label: "Bug Category"
      description: "Which area of the application is affected?"
      options:
        - "1.1 Graphical Gate Layout"
        - "1.2 Gate Wiring"
        - "1.3 Simulation Capabilities"
        - "1.4 Hierarchical Design"
        - "1.5 Design Overview"
        - "UI/UX Issues"
        - "Performance Issues"
        - "Build/Development Issues"
        - "Documentation Issues"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is this bug?"
      options:
        - "Low - Minor issue that doesn't prevent use"
        - "Medium - Issue affects functionality but workarounds exist"
        - "High - Major functionality is broken"
        - "Critical - Application is unusable or data loss occurs"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment Information"
      description: "Provide details about your environment"
      placeholder: |
        - Operating System: [e.g., Windows 11, macOS 13, Ubuntu 22.04]
        - Browser: [e.g., Chrome 119, Firefox 120, Safari 17]
        - .NET Version: [if applicable]
        - AI Logica Version/Commit: [if known]
      value: |
        - Operating System: 
        - Browser: 
        - .NET Version: 
        - AI Logica Version/Commit: 

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or Error Messages"
      description: "Include any screenshots, error messages, or console output"
      placeholder: "Attach screenshots or paste error messages here..."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other context about the problem"
      placeholder: "Is this a regression? Does it happen consistently? Any other relevant information..."

  - type: checkboxes
    id: bug-investigation-checklist
    attributes:
      label: "Developer Investigation Checklist"
      description: "For developers investigating this bug (reference DEVELOPER_GUIDE.md)"
      options:
        - label: "⚠️ CRITICAL: Install git hooks using `script/setup-git-hooks` before starting"
        - label: "Reproduce the issue locally using provided steps"
        - label: "Identify the root cause and affected components"
        - label: "Check if this violates any requirements in REQUIREMENTS.md"
        - label: "Determine if this is a regression from recent changes"
        - label: "Write unit tests that reproduce the bug"
        - label: "Implement fix following coding standards in DEVELOPER_GUIDE.md"
        - label: "Verify fix doesn't break existing functionality with `script/test`"
        - label: "Run `script/format` to ensure code formatting is correct"
        - label: "Test fix in development environment using `script/server`"
        - label: "Update documentation if the fix changes behavior"

  - type: textarea
    id: ai-developer-guidance
    attributes:
      label: "🤖 AI Developer Bug Fix Guide"
      description: "Comprehensive guidance for AI developers fixing this bug"
      value: |
        ## For AI Developers fixing this bug:
        
        ### ⚠️ CRITICAL SETUP STEPS:
        1. **CRITICAL FIRST STEP**: Run `script/setup-git-hooks` to install git hooks before any development work
        2. **Complete setup**: Run `script/setup` to install dependencies and verify environment
        3. **Review documentation**: Read REQUIREMENTS.md, DEVELOPER_GUIDE.md, and ARCHITECTURE.md
        
        ### 🐛 BUG FIX WORKFLOW:
        4. **Reproduce locally**: Follow the steps provided to confirm the issue
        5. **Write tests first**: Create failing tests that demonstrate the bug
        6. **Implement fix**: Make minimal changes to resolve the issue
        7. **Verify solution**: Ensure tests pass and no regressions occur
        8. **Format code**: Use `script/format` before committing
        9. **Test in development**: Verify fix works using `script/server`
        
        ### 🛠️ DEVELOPMENT SCRIPTS:
        - `script/setup` - Complete setup for development
        - `script/setup-git-hooks` - Install git hooks (CRITICAL first step)
        - `script/server` - Start development server for testing
        - `script/test` - Run all tests
        - `script/format` - Format code
        - `script/check-git-hooks` - Verify git hooks are installed
        - `script/cibuild` - Run CI checks locally
    validations:
      required: false