name: 🚀 Feature Request
description: Request new functionality or enhancements to AI Logica
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for proposing a new feature for AI Logica! This template will help ensure your request includes all the information needed for effective implementation, especially by AI developers.
        
        📖 **Please review the existing documentation first:**
        - [REQUIREMENTS.md](../blob/main/REQUIREMENTS.md) - Current functional requirements
        - [DEVELOPER_GUIDE.md](../blob/main/DEVELOPER_GUIDE.md) - Development guidelines and standards
        - [ARCHITECTURE.md](../blob/main/ARCHITECTURE.md) - Technical architecture overview

  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "Describe the feature from the user's perspective"
      placeholder: "As a [user type], I want [goal] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Provide a detailed description of the requested functionality"
      placeholder: "Describe what the feature should do, how it should behave, and any specific requirements..."
    validations:
      required: true

  - type: textarea
    id: functional-requirements
    attributes:
      label: "Functional Requirements"
      description: "Describe the specific functional requirements for this feature. The AI developer will assign appropriate requirement IDs and integrate with existing requirements."
      placeholder: |
        Describe what the system must do to implement this feature:
        - The system must be able to [specific capability]
        - Users must be able to [specific action]
        - The feature must support [specific behavior]
        - The system must validate [specific conditions]
        - The feature must integrate with [existing functionality]
      value: |
        - 
        - 
        - 
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: "Feature Category"
      description: "Which area of the application does this feature relate to?"
      options:
        - "1.1 Graphical Gate Layout"
        - "1.2 Gate Wiring"
        - "1.3 Simulation Capabilities"
        - "1.4 Hierarchical Design"
        - "1.5 Design Overview"
        - "2. Technical Requirements"
        - "UI/UX Improvements"
        - "Performance Enhancements"
        - "Developer Experience"
        - "Testing Infrastructure"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: technical-considerations
    attributes:
      label: "Technical Implementation Considerations"
      description: "Provide guidance for developers implementing this feature"
      placeholder: |
        - Which components/classes likely need modification?
        - Are there any architectural patterns that should be followed?
        - What existing functionality might be affected?
        - Are there any performance or compatibility concerns?
        - Should this integrate with existing features?

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Define what constitutes successful implementation"
      placeholder: |
        - [ ] User can [specific action]
        - [ ] System responds with [expected behavior]
        - [ ] Feature integrates with [existing functionality]
        - [ ] Performance meets [specific criteria]
      value: |
        - [ ] 
        - [ ] 
        - [ ] 

  - type: textarea
    id: testing-strategy
    attributes:
      label: "Testing Strategy"
      description: "How should this feature be tested? Reference E2E_TESTING_STRATEGY.md for current approach"
      placeholder: |
        - Unit tests needed for [components]
        - Component tests for [UI behaviors]
        - Integration tests for [workflows]
        - Any special testing considerations?

  - type: checkboxes
    id: development-checklist
    attributes:
      label: "Development Implementation Checklist"
      description: "For developers implementing this feature (reference DEVELOPER_GUIDE.md)"
      options:
        - label: "⚠️ CRITICAL: Install git hooks using `script/setup-git-hooks` before starting"
        - label: "Review and understand all functional requirements"
        - label: "Analyze functional requirements and assign appropriate FR-X.Y IDs"
        - label: "Update REQUIREMENTS.md with new functional requirements using assigned IDs"
        - label: "Follow coding standards defined in DEVELOPER_GUIDE.md"
        - label: "Implement unit tests following the existing test patterns"
        - label: "Implement component tests for UI changes"
        - label: "Update documentation if new APIs or workflows are introduced"
        - label: "Run `script/test` to ensure all tests pass"
        - label: "Run `script/format` to ensure code formatting is correct"
        - label: "Verify feature works in development using `script/server`"

  - type: textarea
    id: mockups-or-examples
    attributes:
      label: "Mockups, Examples, or References"
      description: "Include any visual mockups, code examples, or references that would help with implementation"
      placeholder: "Attach files, provide links, or describe visual/behavioral examples..."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature?"
      options:
        - "Low - Nice to have"
        - "Medium - Would improve user experience"
        - "High - Important for core functionality"
        - "Critical - Blocking other work"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other information that would be helpful for implementation"
      placeholder: "Related issues, dependencies, constraints, or other relevant information..."

  - type: textarea
    id: ai-developer-guidance
    attributes:
      label: "🤖 AI Developer Implementation Guide"
      description: "Comprehensive guidance for AI developers implementing this feature"
      value: |
        ## For AI Developers implementing this feature:
        
        ### ⚠️ CRITICAL SETUP STEPS:
        1. **CRITICAL FIRST STEP**: Run `script/setup-git-hooks` to install git hooks before any development work
        2. **Complete setup**: Run `script/setup` to install dependencies and verify environment  
        3. **Review documentation**: Read REQUIREMENTS.md, DEVELOPER_GUIDE.md, and ARCHITECTURE.md
        
        ### 📋 IMPLEMENTATION WORKFLOW:
        4. **Analyze requirements**: Review the functional requirements above, assign appropriate FR-X.Y IDs, and identify any conflicts with existing requirements that need resolution
        5. **Understand testing**: Review E2E_TESTING_STRATEGY.md for testing approach
        6. **Follow the pattern**: Use existing code as examples for implementation patterns
        7. **Update requirements**: Add new functional requirements to REQUIREMENTS.md with proper IDs
        8. **Test thoroughly**: Run `script/test` frequently during development
        9. **Format code**: Use `script/format` before committing
        10. **Verify in development**: Test feature works using `script/server`
        
        ### 🛠️ DEVELOPMENT SCRIPTS:
        - `script/setup` - Complete setup for development
        - `script/setup-git-hooks` - Install git hooks (CRITICAL first step)
        - `script/server` - Start development server
        - `script/test` - Run all tests
        - `script/format` - Format code
        - `script/check-git-hooks` - Verify git hooks are installed
        - `script/cibuild` - Run CI checks locally
    validations:
      required: false